# -*- coding: utf-8 -*-
__author__ = 'Seven'

N = {}
N["$Announcements"] = "Anúncios"
N["$Discussions"] = "Discussões"
N["$Off Topic"] = "Off Topic"
N["$Forum Games"] = "Jogos do fórum"
N["$Tribes"] = "Tribos"
N["$Map Submissions"] = "Avaliação de Mapas"
N["$Map Editor"] = " Editor de Mapas"
N["$Modules"] = "Modules"
N["$Fanart"] = "Fanart"
N["$Suggestions"] = "Sugestões"
N["$Bugs"] = "Bugs"
N["$Archives"] = "Arquivos"
N["$Forums"] = "Fóruns"
N["$GO"] = "GO"
N["$Started by"] = "Iniciado por <span class='cadre-type-auteur-{0}'>{1}</span> em <span class="">{2}</span></a>"
N["$Profile"] = "Perfil"
N["$Last Edit"] = "Última edição  <span class="">{0}</span>"
N["$Topic"] = "Tópico"

N["$My Profile"] = "Meu perfil"
N["$My Account"] = "Minha conta"
N["$Last posts"] = "Últimos posts"
N["$Micepix images"] = "Imagens enviadas"
N["$English"] = "Inglesa"
N["$International"] = "Internacional"
N["$Brazilian"] = "Brasileira"
N["$Spanish"] = "Espanhola"
N["$Turkish"] = "Turca"
N["$Polish"] = "Polandesa"
N["$Hungarian"] = "Húngara"
N["$Romanian"] = "Romena"
N["$Azerbaijanese"] = "Azerbaijano"
N["$French"] = "Francesa"
N["$Czech"] = "Tcheca"
N["$Russian"] = "Russa"
N["$Community"] = "Comunidade"
N["$Gender"] = "Sexo"
N["$Location"] = "Localização"
N["$Birthday"] = "Data de nascimento"
N["$Registration date"] = "Data de inscrição"
N["$Presentation"] = "Apresentação"
N["$Online"] = "Online"
N["$Offline"] = "Offline"
N["$Male"] = "Masculino"
N["$Female"] = "Femenino"
N["$Change avatar"] = "Mudar avatar"
N["$Remove avatar"] = "Remover avatar"
N["$Edit"] = "Editar"
N["$Preview"] = "Pré-visualização"
N["$Hide"] = "Ocultar"
N["$Submit"] = "Validar"
N["$Message"] = "Mensagem"
N["$Answer"] = "Responder"
N["$Quote"] = "Citar"
N["$Edit profile"] = "Editar perfil"
N["$Profile"] = "Perfil"
N["$Messages"] = "Mensagens"
N["$New topic"] = "Novo tópico"
N["$Cancel"] = "Cancelar"
N["$Reason"] = "Razón"
N["$Moderated"] = '<span class="cadre-message-modere-texte">[Moderado por {0} motivo : {1}]</span>'
N["$Login"] = "Desconectar"
N["$Log out"] = "Conexão"
N["$UName"] = "Apelido"
N["$Password"] = "Senha"
N["$Upload_Avatar"] = "Carregar avatar"
N["$Preview"] = "Pré-visualização"
N["$Hide"] = "Ocultar"
N["$Submit"] = "Validar"
N["$Message"] = "Mensagem"
N["$Answer"] = "Responder"
N["$Quote"] = "Citar"
N["$Title"] = "Título"
N["$New topic"] = "Novo tópic"
N["$New message"] = "Novo ensagem"
N["$Invalid_param"] = "A solicitação contém um ou mais parâmetros inválidos."
N["$Manage"] = "Administrar"
N["$Close"] = "Fechar"
N["$Moderate"] = "Moderar"
N["$Source"] = "Fonte"
N["$Edit"] = "Editar"

#Micepix
N["$Link to this page"] = "Link para essa página"
N["$Link to image"] = "Link para a imagem"
N["$Embed in forum message"] = "Anexado na mensagem do fórum"
N["$Image"] = "Image"
N["$File"] = "Arquivo"
N["$Link"] = "Link"
N["$Add to gallery"] = "Adicionar à galeria"
N["$Select or drag file"] = "Selecionar ou arrastar arquivo"

#
N["$Profiles"] = "Perfis"
N["$Inbox"] = "Caixa de entrada"
N["$My friends"] = "Meus amigos"
N["$Blacklist"] = "Ignorados"

N["$Report"] = "Reportar"

N["$New discussion"] = "Nova Discussão"
N["$Select all"] = "Selecionar tudo"
N["$Delete"] = "Deletar"
N["$Unselect all"] = "Desmarcar tudo"
N["$Invite"] = "Convidar"
N["$excluded"] = "Saiu"
N["$author"] = "Autor"
N["$invited"] = "Convidado"
N["$Discussion"] = "Discussão"
N["$Exclude"] = "Excluir"
