# -*- coding: utf-8 -*-
__author__ = 'Seven'

N = {}

N["$Announcements"] = "Announcements"
N["$Discussions"] = "Discussions"
N["$Off Topic"] = "Off Topic"
N["$Forum Games"] = "Forum Games"
N["$Tribes"] = "Tribes"
N["$Map Submissions"] = "Map Submissions"
N["$Map Editor"] = "Map Editor"
N["$Modules"] = "Modules"
N["$Fanart"] = "Fanart"
N["$Suggestions"] = "Suggestions"
N["$Bugs"] = "Bugs"
N["$Archives"] = "Archives"
N["$Forums"] = "Forums"
N["$GO"] = "GO"
N["$Started by"] = "Started by <span class='cadre-type-auteur-{0}'>{1}</span> on <span class="">{2}</span></a>"
N["$Profile"] = "Profile"
N["$Last Edit"] = "Last edit on <span class="">{0}</span>"
N["$Topic"] = "Topic"

N["$My Profile"] = "My Profile"
N["$My Account"] = "My Account"
N["$Last posts"] = "Last posts"
N["$Micepix images"] = "Micepix images"
N["$English"] = "English"
N["$International"] = "International"
N["$Brazilian"] = "Brazilian"
N["$Spanish"] = "Spanish"
N["$Turkish"] = "Turkish"
N["$Polish"] = "Polish"
N["$Hungarian"] = "Hungarian"
N["$Romanian"] = "Romanian"
N["$Azerbaijanese"] = "Azerbaijanese"
N["$French"] = "French"
N["$Czech"] = "Czech"
N["$Russian"] = "Russian"
N["$Community"] = "Community"
N["$Gender"] = "Gender"
N["$Location"] = "Location"
N["$Birthday"] = "Birthday"
N["$Registration date"] = "Registration date"
N["$Presentation"] = "Presentation"
N["$Online"] = "Online"
N["$Offline"] = "Offline"
N["$Male"] = "Male"
N["$Female"] = "Female"
N["$Change avatar"] = "Change avatar"
N["$Remove avatar"] = "Remove avatar"
N["$Edit"] = "Edit"
N["$Preview"] = "Preview"
N["$Hide"] = "Hide"
N["$Submit"] = "Submit"
N["$Message"] = "Message"
N["$Answer"] = "Answer"
N["$Quote"] = "Quote"
N["$Edit profile"] = "Edit profile"
N["$Profile"] = "Profile"
N["$Messages"] = "Messages"
N["$New topic"] = "New topic"
N["$Cancel"] = "Cancel"
N["$Reason"] = "Reason"
N["$Moderated"] = '<span class="cadre-message-modere-texte">[{0} tarafından müdahale edildi, sebep : {1}]</span>'
N["$Login"] = "Log in"
N["$Log out"] = "Log out"
N["$UName"] = "Nickname"
N["$Password"] = "Password"
N["$Upload_Avatar"] = "Upload avatar"
N["$Preview"] = "Preview"
N["$Hide"] = "Hide"
N["$Submit"] = "Submit"
N["$Message"] = "Message"
N["$Answer"] = "Answer"
N["$Quote"] = "Quote"
N["$Title"] = "Title"
N["$New topic"] = "New topic"
N["$New message"] = "New message"
N["$Invalid_param"] = "The request contains one or more invalid parameters."
N["$Manage"] = "Manage"
N["$Close"] = "Close"
N["$Moderate"] = "Moderate"
N["$Source"] = "Source"
N["$Edit"] = "Edit"

#Micepix
N["$Link to this page"] = "Link to this page"
N["$Link to image"] = "Link to image"
N["$Embed in forum message"] = "Embed in forum message"
N["$Image"] = "Image"
N["$File"] = "File"
N["$Link"] = "Link"
N["$Add to gallery"] = "Add to gallery"
N["$Select or drag file"] = "Select or drag file"

#
N["$Profiles"] = "Profiles"
N["$Inbox"] = "Inbox"
N["$My friends"] = "My friends"
N["$Blacklist"] = "Blacklist"

N["$Report"] = "Report"