# -*- coding: utf-8 -*-
__author__ = 'Seven'

N = {}
N["$Announcements"] = "Duyurular"
N["$Discussions"] = "Tartışmalar"
N["$Off Topic"] = "Konu Dışı"
N["$Forum Games"] = "Forum Oyunları"
N["$Tribes"] = "Kabileler"
N["$Map Submissions"] = "Harita Yollama"
N["$Map Editor"] = "Harita Editörü"
N["$Modules"] = "Modüller"
N["$Fanart"] = "Hayran Eserleri"
N["$Suggestions"] = "Öneriler"
N["$Bugs"] = "Hatalar"
N["$Archives"] = "Arşiv"
N["$Forums"] = "Forumlar"
N["$GO"] = "GİT"
N["$Started by"] = "<span class='cadre-type-auteur-{0}'>{1}</span> tarafından <span class="">{2}</span>'da açıldı </a>"
N["$Profile"] = "Profil"
N["$Last Edit"] = "Son Düzenleme <span class="">{0}</span>"
N["$Topic"] = "Konu"
N["$My Profile"] = "Profilim"
N["$My Account"] = "Hesap"
N["$Last posts"] = "Son gönderiler"
N["$Micepix images"] = "Yüklenen resimler"
N["$English"] = "İngilizce"
N["$International"] = "Uluslararası"
N["$Brazilian"] = "Brezilya Portekizcesi"
N["$Spanish"] = "İspanyolca"
N["$Turkish"] = "Türkçe"
N["$Polish"] = "Lehçe"
N["$Hungarian"] = "Macarca"
N["$Romanian"] = "Rumence"
N["$Azerbaijanese"] = "Azerice"
N["$French"] = "Fransızca"
N["$Czech"] = "Çekçe"
N["$Russian"] = "Rusça"
N["$Community"] = "Topluluk"
N["$Gender"] = "Cinsiyet"
N["$Location"] = "Konum"
N["$Birthday"] = "Doğum günü"
N["$Registration date"] = "Kayıt tarihi"
N["$Presentation"] = "Tanım"
N["$Online"] = "Çevrimiçi"
N["$Offline"] = "Çevrimdışı"
N["$Male"] = "Erkek"
N["$Female"] = "Kız"
N["$Change avatar"] = "Avatarı değiştir"
N["$Remove avatar"] = "Avatarı kaldır"
N["$Edit"] = "Düzenle"
N["$Preview"] = "Önizleme"
N["$Hide"] = "Gizle"
N["$Submit"] = "Onayla"
N["$Message"] = "Mesaj"
N["$Answer"] = "Yanıtla"
N["$Quote"] = "Alıntıla"
N["$Edit profile"] = "Profili düzenle"
N["$Messages"] = "Mesajlar"
N["$Moderated"] = '<span class="cadre-message-modere-texte">[{0} tarafından müdahale edildi, sebep : {1}]</span>'

N["$Login"] = "Giriş"
N["$Log out"] = "Çıkış"
N["$UName"] = "Kullanıcı adı"
N["$Password"] = "Şifre"
N["$New_thread"] = "Yeni konu"
N["$Upload_Avatar"] = "Avatar yükle"
N["$Title"] = "Başlık"
N["$New_topic"] = "Yeni konu"
N["$Invalid_param"] = "Bir ya da daha fazla geçersiz parametre istendi."
N["$Manage"] = "Yönet"
N["$Close"] = "Kapat"
N["$Moderate"] = "Müdahele et"
N["$Cancel"] = "İptal"
N["$Reason"] = "Sebep"
N["$New messsage"] = "Yeni mesaj"

#Micepix
N["$Link to this page"] = "Sayfa bağlantısı"
N["$Link to image"] = "Resim bağlantısı"
N["$Embed in forum message"] = "Forum mesajına gömülmüş"
N["$Image"] = "Resim"
N["$File"] = "Dosya"
N["$Link"] = "Bağlantı"
N["$Add to gallery"] = "Galeriye ekle"
N["$Select or drag file"] = "Dosyayı seç ya da sürükle"

#
N["$Profiles"] = "Profiller"
N["$Inbox"] = "Gelen kutusu"
N["$My friends"] = "Arkadaşlarım"
N["$Blacklist"] = "Engellenenler"
